[package]
name = "rustsbi"
description = "Minimal RISC-V's SBI implementation library in Rust"
version = "0.3.0-alpha.1"
authors = [
    "Luo Jia <me@luojia.cc>",
    "Campbell He <hkp18@mails.tsinghua.edu.cn>",
    "Yifan Wu <shinbokuow@163.com>",
]
repository = "https://github.com/rustsbi/rustsbi"
documentation = "https://docs.rs/rustsbi"
license = "MulanPSL-2.0 OR MIT"
readme = "README.md"
keywords = ["riscv", "sbi", "rustsbi"]
categories = ["os", "embedded", "hardware-support", "no-std"]
edition = "2021"

[dependencies]
riscv = "0.8"
sbi-spec = { git = "https://github.com/rustsbi/sbi-spec.git", rev = "9d728bb" }
# The following two dependencies are used to support legacy console feature
embedded-hal = { version = "1.0.0-alpha.8", optional = true }
nb = { version = "1.0", optional = true }

[features]
default = []
# Support legacy extension; this feature is not included by default.
legacy = ["embedded-hal", "nb"]
# Dynamic pointer widths on SBI implementations; useful for developing hypervisors
guest = []

[package.metadata.docs.rs]
default-target = "riscv64imac-unknown-none-elf"
targets = [
    "riscv32imac-unknown-none-elf", "riscv64imac-unknown-none-elf",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
